version: '3.8'

services:

  mock-api:
    image: nearby-places-mock-api
    build: ./mock-api
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/healthz || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
    environment:
      - PORT=8080
      - MOCK_API_URL=http://mock-api:3000/nearbyPlaces
    ports:
      - 8080:8080
    depends_on:
      mock-api:
        condition: service_healthy
    restart: unless-stopped
