name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build_server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run eslint and prettier
        run: bun run lint

      - name: Build bun bundle
        run: bun run build

      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v2
        with:
          # Mockoon CLI version, default to 'latest'
          version: "6.2.0"
          # Mockoon local data file or URL
          data-file: "../mock-api/nearby-places-mock-api.json"
          # port, default to 3000
          port: 3000

      - name: Test Mockoon healthcheck
        run: curl -X GET http://localhost:3000/healthz

      - name: Test Mockoon API /nearbyPlaces
        run: curl -X GET http://localhost:3000/nearbyPlaces

      - name: Run tests
        env:
          MOCK_API_URL: http://localhost:3000/nearbyPlaces
        run: bun test
